# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.daemon=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Hilt
dagger.hilt.disableModulesHaveInstallInCheck=false
